7za a -tzip mx140.zip -pCuong09.10 *.cpp *.html *.txt *.py *.hpp *.c *.java -r
set /p DUMMY=Press ENTER to exit...

7za a -t7z mx140.7z -r ".lib\*.cpp" ".lib\*.hpp"
set /p DUMMY=Press ENTER to exit...