# Generated by iptables-save v1.8.7 on Wed Nov 20 08:17:01 2024
*filter
:INPUT ACCEPT [2745:291790]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [17179:2800092]
:ts-forward - [0:0]
:ts-input - [0:0]
-A INPUT -j ts-input
-A INPUT -p udp -m udp --dport 9001 -j ACCEPT
-A FORWARD -j ts-forward
-A FORWARD -i eth0 -o tailscale0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i tailscale0 -o eth0 -j ACCEPT
-A ts-forward -i tailscale0 -j MARK --set-xmark 0x40000/0xff0000
-A ts-forward -m mark --mark 0x40000/0xff0000 -j ACCEPT
-A ts-forward -s 100.64.0.0/10 -o tailscale0 -j ACCEPT
-A ts-forward -o tailscale0 -j ACCEPT
-A ts-input -s 100.64.0.6/32 -i lo -j ACCEPT
-A ts-input -s 100.115.92.0/23 ! -i tailscale0 -j RETURN
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j ACCEPT
-A ts-input -i tailscale0 -j ACCEPT
-A ts-input -p udp -m udp --dport 41641 -j ACCEPT
COMMIT

# Completed on Wed Nov 20 08:17:01 2024
# Generated by iptables-save v1.8.7 on Wed Nov 20 08:17:01 2024
*nat
:PREROUTING ACCEPT [734:83522]
:INPUT ACCEPT [212:12939]
:OUTPUT ACCEPT [564:51617]
:POSTROUTING ACCEPT [564:51617]
:ts-postrouting - [0:0]
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
-A POSTROUTING -j ts-postrouting
-A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE
COMMIT