curl -fsSL https://tailscale.com/install.sh | sh


echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
sudo sysctl -p /etc/sysctl.d/99-tailscale.conf


# udp gro
NETDEV=$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")
sudo ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off

printf '#!/bin/sh\n\nethtool -K %s rx-udp-gro-forwarding on rx-gro-list off \n' "$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")" | sudo tee /etc/networkd-dispatcher/routable.d/50-tailscale
sudo chmod 755 /etc/networkd-dispatcher/routable.d/50-tailscale

sudo /etc/networkd-dispatcher/routable.d/50-tailscale
test $? -eq 0 || echo 'An error occurred.'

#start
sudo tailscale up --advertise-exit-node --accept-routes=true

sudo tailscale status
100.64.0.6      bizfly-vps           NTC09@       linux   idle; offers exit node; offline
100.64.0.8      aws-sing             NTC09@       linux   idle; offers exit node
100.64.0.7      desktop-vf9d3d0      NTC09@       windows offline
100.64.0.3      predator             NTC09@       windows active; direct 42.114.171.171:32625, tx 503720 rx 1912680
100.64.0.4      s24u                 NTC09@       android active; direct [2401:d800:7271:b0f6:9943:7e21:bbaa:7a92]:47377, tx 82476 rx 71908
100.64.0.5      ts10u                NTC09@       android offline
100.64.0.2      vultr                NTC09@       linux   idle; offers exit node

#forward
sudo apt install netfilter-persistent

sudo iptables-save
# Generated by iptables-save v1.8.10 (nf_tables) on Wed Nov 20 09:11:09 2024
*filter
:INPUT ACCEPT [3575:348089]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ts-forward - [0:0]
:ts-input - [0:0]
-A INPUT -j ts-input
-A FORWARD -j ts-forward
-A ts-forward -i tailscale0 -j MARK --set-xmark 0x40000/0xff0000
-A ts-forward -m mark --mark 0x40000/0xff0000 -j ACCEPT
-A ts-forward -s 100.64.0.0/10 -o tailscale0 -j DROP
-A ts-forward -o tailscale0 -j ACCEPT
-A ts-input -s 100.64.0.6/32 -i lo -j ACCEPT
-A ts-input -s 100.115.92.0/23 ! -i tailscale0 -j RETURN
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
-A ts-input -i tailscale0 -j ACCEPT
-A ts-input -p udp -m udp --dport 41641 -j ACCEPT
COMMIT
# Completed on Wed Nov 20 09:11:09 2024
# Generated by iptables-save v1.8.10 (nf_tables) on Wed Nov 20 09:11:09 2024
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [353:26872]
:ts-postrouting - [0:0]
-A POSTROUTING -j ts-postrouting
-A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE
COMMIT
# Completed on Wed Nov 20 09:11:09 2024


sudo iptables -t nat -A PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001
sudo iptables -t nat -A PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
sudo iptables -t nat -A PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001

sudo iptables -t nat -A PREROUTING -p tcp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001
sudo iptables -t nat -A PREROUTING -p tcp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
sudo iptables -t nat -A PREROUTING -p tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001

sudo netfilter-persistent save && sudo netfilter-persistent reload

sudo iptables-save

sudo iptables -L -n

sudo iptables -t nat -L -n -v

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ts-input   0    --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ts-forward  0    --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain ts-forward (1 references)
target     prot opt source               destination         
MARK       0    --  0.0.0.0/0            0.0.0.0/0            MARK xset 0x40000/0xff0000
ACCEPT     0    --  0.0.0.0/0            0.0.0.0/0            mark match 0x40000/0xff0000
DROP       0    --  100.64.0.0/10        0.0.0.0/0           
ACCEPT     0    --  0.0.0.0/0            0.0.0.0/0           

Chain ts-input (1 references)
target     prot opt source               destination         
ACCEPT     0    --  100.64.0.6           0.0.0.0/0           
RETURN     0    --  100.115.92.0/23      0.0.0.0/0           
DROP       0    --  100.64.0.0/10        0.0.0.0/0           
ACCEPT     0    --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     17   --  0.0.0.0/0            0.0.0.0/0            udp dpt:41641

# 
sudo nano /etc/sysctl.conf
net.ipv4.ip_forward=1
sudo sysctl -p

# s10 can connect, s24 cannot

sudo iptables -A INPUT -p tcp --dport 9001 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 9001 -j ACCEPT

# Generated by iptables-save v1.8.10 (nf_tables) on Wed Nov 20 09:55:21 2024
*filter
:INPUT ACCEPT [28592:2849713]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ts-forward - [0:0]
:ts-input - [0:0]
-A INPUT -j ts-input
-A INPUT -p tcp -m tcp --dport 9001 -j ACCEPT
-A INPUT -p udp -m udp --dport 9001 -j ACCEPT
-A FORWARD -j ts-forward
-A ts-forward -i tailscale0 -j MARK --set-xmark 0x40000/0xff0000
-A ts-forward -m mark --mark 0x40000/0xff0000 -j ACCEPT
-A ts-forward -s 100.64.0.0/10 -o tailscale0 -j DROP
-A ts-forward -o tailscale0 -j ACCEPT
-A ts-input -s 100.64.0.6/32 -i lo -j ACCEPT
-A ts-input -s 100.115.92.0/23 ! -i tailscale0 -j RETURN
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
-A ts-input -i tailscale0 -j ACCEPT
-A ts-input -p udp -m udp --dport 41641 -j ACCEPT
COMMIT
# Completed on Wed Nov 20 09:55:21 2024
# Generated by iptables-save v1.8.10 (nf_tables) on Wed Nov 20 09:55:21 2024
*nat
:PREROUTING ACCEPT [3786:432805]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [3965:314058]
:ts-postrouting - [0:0]
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001

-A POSTROUTING -j ts-postrouting
-A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE
COMMIT
# Completed on Wed Nov 20 09:55:21 2024


# last work

# Generated by iptables-save v1.8.10 (nf_tables) on Wed Nov 20 10:29:20 2024
*filter
:INPUT ACCEPT [48486:5030039]
:FORWARD ACCEPT [1106:93890]
:OUTPUT ACCEPT [0:0]
:ts-forward - [0:0]
:ts-input - [0:0]
iptables -A INPUT -j ts-input
iptables -A INPUT -p tcp -m tcp --dport 9001 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 9001 -j ACCEPT
iptables -A FORWARD -j ts-forward
iptables -A ts-forward -i tailscale0 -j MARK --set-xmark 0x40000/0xff0000
iptables -A ts-forward -m mark --mark 0x40000/0xff0000 -j ACCEPT
iptables -A ts-forward -s 100.64.0.0/10 -o tailscale0 -j DROP
iptables -A ts-forward -o tailscale0 -j ACCEPT
iptables -A ts-input -s 100.64.0.6/32 -i lo -j ACCEPT
iptables -A ts-input -s 100.115.92.0/23 ! -i tailscale0 -j RETURN
iptables -A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
iptables -A ts-input -i tailscale0 -j ACCEPT
iptables -A ts-input -p udp -m udp --dport 41641 -j ACCEPT
COMMIT
# Completed on Wed Nov 20 10:29:20 2024
# Generated by iptables-save v1.8.10 (nf_tables) on Wed Nov 20 10:29:20 2024
*nat
:PREROUTING ACCEPT [7161:760980]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [7561:614450]
:ts-postrouting - [0:0]
-A PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
-A PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
-A POSTROUTING -j ts-postrouting
-A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE
COMMIT
# Completed on Wed Nov 20 10:29:20 2024

sudo iptables -t nat -A PREROUTING -p udp --dport 9000 -j DNAT --to-destination 100.64.0.3:9000
sudo iptables -t nat -A PREROUTING -p tcp --dport 9000 -j DNAT --to-destination 100.64.0.3:9000

sudo iptables -t nat -A PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
sudo iptables -t nat -A PREROUTING -p tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001

sudo iptables -t nat -A PREROUTING -p udp --dport 9000 -j DNAT --to-destination 100.64.0.3:9001
sudo iptables -t nat -A PREROUTING -p tcp --dport 9000 -j DNAT --to-destination 100.64.0.3:9001

sudo iptables -t nat -A PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.4:9000
sudo iptables -t nat -A PREROUTING -p tcp --dport 9001 -j DNAT --to-destination 100.64.0.4:9000


sudo iptables -t nat -D PREROUTING -p udp --dport 9000 -j DNAT --to-destination 100.64.0.3:9000
sudo iptables -t nat -D PREROUTING -p tcp --dport 9000 -j DNAT --to-destination 100.64.0.3:9000

sudo iptables -t nat -D PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
sudo iptables -t nat -D PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001

#moonlight


sudo iptables -t nat -A PREROUTING -p tcp --dport 47984 -j DNAT --to-destination 100.64.0.3:47984
sudo iptables -t nat -A PREROUTING -p tcp --dport 47989 -j DNAT --to-destination 100.64.0.3:47989
sudo iptables -t nat -A PREROUTING -p tcp --dport 48010 -j DNAT --to-destination 100.64.0.3:48010

sudo iptables -t nat -A PREROUTING -p udp --dport 47998 -j DNAT --to-destination 100.64.0.3:47998
sudo iptables -t nat -A PREROUTING -p udp --dport 47999 -j DNAT --to-destination 100.64.0.3:47999
sudo iptables -t nat -A PREROUTING -p udp --dport 48000 -j DNAT --to-destination 100.64.0.3:48000
sudo iptables -t nat -A PREROUTING -p udp --dport 48002 -j DNAT --to-destination 100.64.0.3:48002
sudo iptables -t nat -A PREROUTING -p udp --dport 48010 -j DNAT --to-destination 100.64.0.3:48010

sudo iptables -t nat -D PREROUTING -p udp -m udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
sudo iptables -t nat -D PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.5:9001
sudo iptables -t nat -D PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.4:9001
sudo iptables -t nat -D PREROUTING -p tcp -m tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001



# save after boot
sudo apt install iptables-persistent

sudo iptables-save > /etc/iptables/rules.v4


sudo iptables -A INPUT -p tcp --dport 47984 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 47989 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 48010 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 47998 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 47999 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 48000 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 48002 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 48010 -j ACCEPT



iptables --table nat -A PREROUTING --dest 1.1.1.1 -p tcp --dport 80 -j DNAT --to-destination 192.168.1.101:80




sudo iptables -t nat -D PREROUTING -p udp -d 127.0.0.1 --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
sudo iptables -D FORWARD -p udp -d 100.64.0.3 --dport 9001 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
sudo iptables -t nat -D POSTROUTING -p udp -s 100.64.0.3 --sport 9001 -j SNAT --to-source 127.0.0.1

sudo iptables -t nat -A OUTPUT -d 100.64.0.3 -j DNAT --to-destination 127.0.0.1
sudo iptables -t nat -A POSTROUTING -d 100.64.0.3 -p tcp --dport 80 -j SNAT --to-source 203.0.113.10
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT


sudo iptables -t nat -D PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.3:80
sudo iptables -t nat -D POSTROUTING -d 100.64.0.3 -p udp --dport 9001 -j SNAT --to-source 18.142.227.62
sudo iptables -D INPUT -p udp --dport 9001 -j ACCEPT


sudo iptables -t nat -A PREROUTING -p tcp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
sudo iptables -t nat -A PREROUTING -p udp --dport 9001 -j DNAT --to-destination 100.64.0.3:9001
sudo iptables -A INPUT -p tcp --dport 9001 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 9001 -j ACCEPT
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE


sudo iptables -A INPUT -p tcp --dport 9000:9010 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 9000:9010 -j ACCEPT


curl http://18.142.227.62:9001


sudo iptables -t nat -A PREROUTING -p tcp --dport 9002 -j DNAT --to-destination 100.64.0.9:9002
sudo iptables -t nat -A PREROUTING -p udp --dport 9002 -j DNAT --to-destination 100.64.0.9:9002


sudo netfilter-persistent save && sudo netfilter-persistent reload


sudo iptables -t nat -A PREROUTING -p udp --dport 9000:9010 -j DNAT --to-destination 100.64.0.5:9000-9010


netfilter-persistent flush # dont use
iptables-save flush


sudo iptables -t nat -A PREROUTING -p udp --dport 48001 -j DNAT --to-destination 100.64.0.3:48001


sudo iptables-save

apt-get install iftop -y